name: 'ost_linker'
version: '1.0.0'
config-version: 2

profile: 'ost_linker'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ost_linker:

    ml:
      +materialized: table
      +schema: ml
      raw:
        +meta:
          dagster:
            group: ml_preparation
      staging:
        +meta:
          dagster:
            group: ml_preparation
      pivot:
        +meta:
          dagster:
            group: ml_preparation
      int:
        +meta:
          dagster:
            group: ml_preparation

    users:
      +enabled: true
      
      staging:
        +materialized: table
        +schema: ml
        +meta:
          dagster:
            group: ml_preparation

      int:
        +materialized: table
        +schema: ml
        +meta:
          dagster:
            group: ml_preparation

      pivot:
        +materialized: table
        +schema: ml
        +meta:
          dagster:
            group: ml_preparation # As requested by user

              
    projects:
      +enabled: true
      
      staging:
        +materialized: table
        +schema: github
        stg_github_project:
          +enabled: true
          +meta:
            dagster:
              group: ingestion
        stg_github_readme:
          +enabled: true
          +meta:
            dagster:
              group: ingestion
        stg_github_topics:
          +enabled: true
          +meta:
            dagster:
              group: ingestion
        stg_github_languages:
          +enabled: true
          +meta:
            dagster:
              group: ingestion
        stg_github_detection:
          +enabled: true
          +meta:
            dagster:
              group: ingestion
              
      int:
        +materialized: table
        +schema: github
        int_github_project:
          +enabled: true
          +meta:
            dagster:
              group: ingestion


      pivot:
        +materialized: table
        pvt_github_project:
          +enabled: true
          +schema: github
          +meta:
            dagster:
              group: ingestion

    match:
      +materialized: table
      +schema: public
      +meta:
        dagster:
          group: matching