########################################
# CONFIGURATION MODULE - OST AI ENGINE (EXAMPLE)
########################################

"""
Generates a sample centralized config YAML for onboarding.
Uses placeholders (no secrets) and a dynamic seven_days_ago
in the GitHub query. Do not use in production.
"""

import os
from datetime import date, timedelta

# Compute a rolling "seven days ago" date used in example GitHub query
seven_days_ago = (date.today() - timedelta(days=7)).isoformat()

github_base_filters = [
    "stars:100..500",
    "topics:>0",
    "forks:>0",
    f"created:>={seven_days_ago}",
    "is:public",
    "archived:false",
    "NOT download"
]

# General (example default)
database_url = os.getenv("DATABASE_URL", "postgresql://user:pass@host:5432/dbname")

GITHUB = {
    "GITHUB_API_URL": os.getenv("GITHUB_API_URL", "https://api.github.com/search/repositories"),
    "GITHUB_ACCESS_TOKEN": os.getenv("GITHUB_ACCESS_TOKEN", "your_github_token_here"),
    # Matches the real `cfg.py` filters but uses a dynamic date in the example generator
    "GITHUB_SCRAPING_QUERY": os.getenv("GITHUB_SCRAPING_QUERY", " ".join(github_base_filters)),
    # Default to the same 6-hour schedule used by `cfg.py`
    "GITHUB_SCRAPER_CRON": os.getenv("GITHUB_SCRAPER_CRON", "0 */6 * * *"),
    "GITHUB_TOP_N": int(os.getenv("GITHUB_TOP_N", "30")),
}

GITLAB = {
    "GITLAB_API_URL": os.getenv("GITLAB_API_URL", "https://gitlab.com/api/v4"),
    "GITLAB_ACCESS_TOKEN": os.getenv("GITLAB_ACCESS_TOKEN", "your_gitlab_token_here"),
    "GITLAB_SCRAPING_QUERY": os.getenv("GITLAB_SCRAPING_QUERY", "opensource"),
    "GITLAB_PROJECTS_VISIBILITY": os.getenv("GITLAB_PROJECTS_VISIBILITY", "public"),
    "GITLAB_PROJECTS_ARCHIVED": os.getenv("GITLAB_PROJECTS_ARCHIVED", "false"),
    "GITLAB_PROJECTS_ORDER_BY": os.getenv("GITLAB_PROJECTS_ORDER_BY", "created_at"),
    "GITLAB_PROJECTS_SORT": os.getenv("GITLAB_PROJECTS_SORT", "desc"),
    "GITLAB_TOP_N": int(os.getenv("GITLAB_TOP_N", "30")),
}

dest_path = os.path.join(os.path.dirname(__file__), "cfg.example.yaml")
with open(dest_path, "w") as f:
    f.write(f"""
############################################################
#  OST AI ENGINE - CENTRALIZED CONFIG (EXAMPLE)            #
#  Generated by cfg.example.py - DO NOT USE FOR PROD       #
############################################################

# ───────────────────────────────────────────────────────── #

# PostgreSQL database connection URL
DATABASE_URL: "{database_url}"

# # GitHub configuration
GITHUB_API_URL: {GITHUB['GITHUB_API_URL']}
GITHUB_ACCESS_TOKEN: "{GITHUB['GITHUB_ACCESS_TOKEN']}"
GITHUB_SCRAPING_QUERY: {GITHUB['GITHUB_SCRAPING_QUERY']}
GITHUB_SCRAPER_CRON: "{GITHUB['GITHUB_SCRAPER_CRON']}"
GITHUB_TOP_N: {GITHUB['GITHUB_TOP_N']}

# GitLab configuration
GITLAB_API_URL: {GITLAB['GITLAB_API_URL']}
GITLAB_ACCESS_TOKEN: "{GITLAB['GITLAB_ACCESS_TOKEN']}"
GITLAB_PROJECTS_VISIBILITY: {GITLAB['GITLAB_PROJECTS_VISIBILITY']}
GITLAB_PROJECTS_ARCHIVED: {GITLAB['GITLAB_PROJECTS_ARCHIVED']}
GITLAB_PROJECTS_ORDER_BY: {GITLAB['GITLAB_PROJECTS_ORDER_BY']}
GITLAB_PROJECTS_SORT: {GITLAB['GITLAB_PROJECTS_SORT']}
GITLAB_SCRAPING_QUERY: {GITLAB['GITLAB_SCRAPING_QUERY']}
GITLAB_TOP_N: {GITLAB['GITLAB_TOP_N']}

# ───────────────────────────────────────────────────────── #
""")