########################################
# CONFIGURATION MODULE - OST AI ENGINE (EXAMPLE)
########################################

"""
Generates a sample centralized config YAML for onboarding.
Uses placeholders (no secrets) and a dynamic seven_days_ago
in the GitHub query. Do not use in production.
"""

import os
from datetime import date, timedelta

# Compute a rolling "seven days ago" date used in example GitHub query
time = (date.today() - timedelta(days="X")).isoformat()

github_base_filters = [
    "stars:X..X",
    "topics:>X",
    "forks:>X",
    f"created:>={time}",
    "is:public",
    "archived:false",
    "NOT download"
]

# General (example default)
database_url = os.getenv("DATABASE_URL", "postgresql://user:pass@host:5432/dbname")

GITHUB = {
    "GITHUB_API_URL": os.getenv("GITHUB_API_URL", "https://api.github.com/search/repositories"),
    "GITHUB_ACCESS_TOKEN": os.getenv("GITHUB_ACCESS_TOKEN", "your_github_token_here"),
    # Matches the real `cfg.py` filters but uses a dynamic date in the example generator
    "GITHUB_SCRAPING_QUERY": os.getenv("GITHUB_SCRAPING_QUERY", " ".join(github_base_filters)),
    "GITHUB_TOP_N": int(os.getenv("GITHUB_TOP_N", "30")),
}

# Optional model / seed paths used by the pipeline
FASTTEXT_MODEL_PATH = os.getenv("FASTTEXT_MODEL_PATH", "/app/models/lid.176.ftz")

dest_path = os.path.join(os.path.dirname(__file__), "cfg.example.yaml")
with open(dest_path, "w") as f:
    f.write(f"""
############################################################
#  OST AI ENGINE - CENTRALIZED CONFIG (EXAMPLE)            #
#  Generated by cfg.example.py - DO NOT USE FOR PROD       #
############################################################

# ───────────────────────────────────────────────────────── #

# PostgreSQL database connection URL
DATABASE_URL: "{database_url}"

# # GitHub configuration
    GITHUB_API_URL: {GITHUB['GITHUB_API_URL']}
    GITHUB_ACCESS_TOKEN: "{GITHUB['GITHUB_ACCESS_TOKEN']}"
    # Quote the scraping query because it contains special characters (colon, >, spaces)
    GITHUB_SCRAPING_QUERY: "{GITHUB['GITHUB_SCRAPING_QUERY']}"
    GITHUB_TOP_N: {GITHUB['GITHUB_TOP_N']}

# Optional model paths used by the pipeline

FASTTEXT_MODEL_PATH: {FASTTEXT_MODEL_PATH}
# ───────────────────────────────────────────────────────── #
""")