########################################
# CONFIGURATION MODULE - OST AI ENGINE (EXAMPLE)
########################################

"""
Generates a sample centralized config YAML for onboarding.
Uses placeholders (no secrets) and a dynamic seven_days_ago
in the GitHub query. Do not use in production.
"""


import os
from datetime import date, timedelta

today = date.today().isoformat()
seven_days_ago = (date.today() - timedelta(days=7)).isoformat()

# General
database_url = os.getenv("DATABASE_URL", "postgresql://dbuser:dbpwd@host:5432/dbname")

# GitHub
github_access_token = os.getenv("GITHUB_ACCESS_TOKEN", "your_github_token_here")
github_scraping_query = os.getenv(
    "GITHUB_SCRAPING_QUERY",
    f"stars:>100 stars:<500 created:>={seven_days_ago} is:public archived:false"
)
github_scraper_cron = os.getenv("GITHUB_SCRAPER_CRON", "0 * * * *")
github_top_n = int(os.getenv("GITHUB_TOP_N", "30"))

# GitLab
gitlab_access_token = os.getenv("GITLAB_ACCESS_TOKEN", "your_gitlab_token_here")
gitlab_scraping_query = os.getenv("GITLAB_SCRAPING_QUERY", "opensource")
gitlab_projects_visibility = os.getenv("GITLAB_PROJECTS_VISIBILITY", "public")
gitlab_projects_archived = os.getenv("GITLAB_PROJECTS_ARCHIVED", "false")
gitlab_projects_order_by = os.getenv("GITLAB_PROJECTS_ORDER_BY", "created_at")
gitlab_projects_sort = os.getenv("GITLAB_PROJECTS_SORT", "desc")
gitlab_top_n = int(os.getenv("GITLAB_TOP_N", "30"))

dest_path = os.path.join(os.path.dirname(__file__), "config.example.yaml")
with open(dest_path, "w") as f:
    f.write(f"""
############################################################
#  OST AI ENGINE - CENTRALIZED CONFIG (EXAMPLE)            #
#  Generated by config.example.py - DO NOT USE FOR PROD    #
############################################################

# ───────────────────────────────────────────────────────── #

# PostgreSQL database connection URL
DATABASE_URL: "{database_url}"

# # GitHub configuration
GITHUB_ACCESS_TOKEN: "{github_access_token}"
GITHUB_SCRAPING_QUERY: {github_scraping_query}
GITHUB_SCRAPER_CRON: "{github_scraper_cron}"
GITHUB_TOP_N: {github_top_n}

# GitLab configuration
GITLAB_ACCESS_TOKEN: "{gitlab_access_token}"
GITLAB_PROJECTS_VISIBILITY: {gitlab_projects_visibility}
GITLAB_PROJECTS_ARCHIVED: {gitlab_projects_archived}
GITLAB_PROJECTS_ORDER_BY: {gitlab_projects_order_by}
GITLAB_PROJECTS_SORT: {gitlab_projects_sort}
GITLAB_SCRAPING_QUERY: {gitlab_scraping_query}
GITLAB_TOP_N: {gitlab_top_n}

# ───────────────────────────────────────────────────────── #
""")