########################################
# CONFIGURATION MODULE - OST AI ENGINE (EXAMPLE)
########################################

"""
Generates a sample centralized config YAML for onboarding.
Uses placeholders (no secrets) and a dynamic seven_days_ago
in the GitHub query. Do not use in production.
"""


import os
from datetime import date, timedelta
import yaml

# Use getenv for all keys, with onboarding-friendly defaults
today = date.today().isoformat()

config_example = {
    "DATABASE_URL": os.getenv("DATABASE_URL", "postgresql://dbuser:dbpwd@host:5432/dbname"),
    "GITHUB_TOP_N": int(os.getenv("GITHUB_TOP_N", "30")),
    "GITHUB_ACCESS_TOKEN": os.getenv("GITHUB_ACCESS_TOKEN", "your_github_token_here"),
    "GITLAB_ACCESS_TOKEN": os.getenv("GITLAB_ACCESS_TOKEN", "your_gitlab_token_here"),
    "GITHUB_SCRAPING_QUERY": os.getenv(
        "GITHUB_SCRAPING_QUERY",
        f"stars:>100 stars:<500 created:>=YYYY-MM-DD is:public archived:false"
    ),
    "GITHUB_SCRAPER_CRON": os.getenv("GITHUB_SCRAPER_CRON", "0 * * * *"),
}

dest_path = os.path.join(os.path.dirname(__file__), "config.example.yaml")
with open(dest_path, "w") as f:
    f.write("""
############################################################
#  OST AI ENGINE - CENTRALIZED CONFIG (EXAMPLE)            #
#  Generated by config.example.py - DO NOT USE FOR PROD    #
############################################################

# ───────────────────────────────────────────────────────── #
# PostgreSQL database connection URL
DATABASE_URL: "{database_url}"

# GitHub access token
GITHUB_ACCESS_TOKEN: "{github_access_token}"

# GitLab access token
GITLAB_ACCESS_TOKEN: "{gitlab_access_token}"

# GitHub scraping query
GITHUB_SCRAPING_QUERY: "{github_scraping_query}"

# Cron schedule for GitHub scraper Dagster job
GITHUB_SCRAPER_CRON: "{github_scraper_cron}"

# Number of top GitHub projects to fetch
GITHUB_TOP_N: {github_top_n}

# ───────────────────────────────────────────────────────── #
""".format(
    database_url=config_example["DATABASE_URL"],
    github_access_token=config_example["GITHUB_ACCESS_TOKEN"],
    gitlab_access_token=config_example["GITLAB_ACCESS_TOKEN"],
    github_scraping_query=config_example["GITHUB_SCRAPING_QUERY"],
    github_scraper_cron=config_example["GITHUB_SCRAPER_CRON"],
    github_top_n=config_example["GITHUB_TOP_N"],
))