name: 'ost_transform'
version: '1.0.0'
config-version: 2

profile: 'ost_transform'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

quoting:
  identifier: true

models:
  ost_transform:
    materialized: table

# Auto-install dependencies
require-dbt-version: ">=1.0.0"

