ost_transform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'password') }}"
      port: "{{ env_var('DB_PORT', '5434') | as_native }}"
      dbname: "{{ env_var('POSTGRES_DB', 'OST_PROD') }}"
      schema: "{{ env_var('DB_SCHEMA', 'public') }}"
      threads: "{{ env_var('DB_THREADS', '4') | as_native }}"

