DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'github_PROJECT',
    'PROJECT',
    'PROJECT_CATEGORY',
    'PROJECT_TECH_STACK',
    'PROJECT_ROLE',
    'PROJECT_GOAL',
    'PROJECT_ROLE_APPLICATION',
    'PROJECT_EXTERNAL_LINK',
    'TEAM_MEMBER',
    'KEY_FEATURE',
    'PROJECT_ROLE_APPLICATION_PROJECT_GOAL',
    'PROJECT_ROLE_APPLICATION_KEY_FEATURE',
    'TEAM_MEMBER_PROJECT_ROLE',
    'PROJECT_ROLE_TECH_STACK',
    'USER_PROJECT_SIMILARITY',
    'embed_PROJECTS',
    'embed_PROJECTS_temp',
    'embed_USERS',
    'hybrid_PROJECT_embeddings',
    'training_PROJECT'
  ]
  LOOP
    EXECUTE format('TRUNCATE TABLE %I RESTART IDENTITY CASCADE;', t);
  END LOOP;
END $$;