name: Publish develop

on:
  pull_request:
    branches: [ main, staging ]
  push:
    branches:
      - staging

jobs:
  checks:
    uses: ./.github/workflows/quality-checks.yml

  build:
    runs-on: ubuntu-latest
    needs: [checks]
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.OST_RELEASE_PAT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/opensource-together/ia
          tags: |
            type=sha
            type=raw,value=develop

      - name: Upload server artifact
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
